version: 2
# 実行環境
executors:
  python_latest_executor:
    docker:
      - image: circleci/python:latest
        environment:
          PIPENV_VENV_IN_PROJECT: true
# jobs
jobs:
  test:
    executor: python_latest_executor
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:  # このステップは依存関係をインストールする*前*に実行します
          key: kueventparser-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies
          command: |  # Pipenv を使用して依存関係をインストールします
            sudo pip install pipenv
            pipenv install --dev
      - save_cache:
          key: kueventparser-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
      - run:
          name: Running tests
          command: | # これで tox が 走る
            pipenv run test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
  # deploy
# workflow
workflows:
  version: 2.1
  "Base Test":
    jobs:
      - test:
#          filters:
#            branches:
#              only:
#                - master
#                - develop
