#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function, unicode_literals
import os
import sys

from eventparser.kyoto_u import get_event
from eventparser.utils import print_event


def show_usage():
    filename = os.path.basename(__file__)
    usage = ("usage: " + filename + " <URL>\n"
             "\n"
             "<URL> is URL of an Kyoto Univ. event page.")
    print(usage)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        show_usage()
        sys.exit(1)
    url = sys.argv[1]
    event = get_event(url)
    print_event(event)